"""Sequence designer GUI with directionality controls and panel guidance.

Deterministic fallback generated by runtime when model-authored implement
actions are unavailable. The scaffold intentionally includes mlapp-style
controls (feeding orientation, read direction, and operator notes panel)
so operator-assistant driven runs stay useful under fallback conditions.
"""

from __future__ import annotations

import tkinter as tk
from tkinter import messagebox, scrolledtext

import matplotlib.pyplot as plt
import numpy as np

from nanoporethon.consensus_maker_gui import consensus_signal, sanitize_sequence


_FEEDING_ORIENTATION_OPTIONS = (
    "5'→3' trans feed",
    "3'→5' cis feed",
)

_READ_DIRECTION_OPTIONS = (
    "left-to-right",
    "right-to-left",
)

_INSTRUCTION_TEXT = (
    "Sequence Designer Notes\n"
    "----------------------\n"
    "1) Paste an A/C/G/T sequence (whitespace is ignored).\n"
    "2) Set k-mer size and feeding/read-direction options.\n"
    "3) Generate to inspect expected consensus current levels.\n"
    "4) Use orientation options to compare strand-context effects.\n"
    "\n"
    "Notation:\n"
    "- Feeding orientation controls strand movement convention.\n"
    "- Read direction controls display ordering of consensus levels.\n"
    "- Current is plotted in normalized I/I0 units.\n"
)


class SequenceDesignerGUI:
    """GUI for sequence-to-consensus previews with mlapp-style controls."""

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Sequence Designer")
        self.root.geometry("1120x700")

        main = tk.Frame(root, padx=10, pady=10)
        main.pack(fill=tk.BOTH, expand=True)

        header = tk.Frame(main)
        header.pack(fill=tk.X, pady=(0, 8))
        tk.Label(
            header,
            text="Sequence Designer",
            font=("TkDefaultFont", 14, "bold"),
            anchor="w",
        ).pack(side=tk.LEFT)
        tk.Label(
            header,
            text="Consensus signal preview from DNA sequence",
            fg="#444444",
        ).pack(side=tk.LEFT, padx=(12, 0))

        content = tk.Frame(main)
        content.pack(fill=tk.BOTH, expand=True)

        left_panel = tk.Frame(content)
        left_panel.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=(0, 10))

        right_panel = tk.Frame(content, width=340)
        right_panel.pack(side=tk.RIGHT, fill=tk.BOTH)
        right_panel.pack_propagate(False)

        tk.Label(left_panel, text="DNA sequence input (A/C/G/T):", anchor="w").pack(fill=tk.X)
        self.sequence_box = scrolledtext.ScrolledText(left_panel, height=12, wrap=tk.WORD)
        self.sequence_box.pack(fill=tk.BOTH, expand=False, pady=(4, 8))

        controls = tk.LabelFrame(left_panel, text="Signal Controls", padx=8, pady=8)
        controls.pack(fill=tk.X)

        row1 = tk.Frame(controls)
        row1.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row1, text="k-mer size:", width=18, anchor="w").pack(side=tk.LEFT)
        self.kmer_var = tk.StringVar(value="5")
        tk.Entry(row1, textvariable=self.kmer_var, width=8).pack(side=tk.LEFT)

        row2 = tk.Frame(controls)
        row2.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row2, text="Feeding orientation:", width=18, anchor="w").pack(side=tk.LEFT)
        self.feed_var = tk.StringVar(value=_FEEDING_ORIENTATION_OPTIONS[0])
        tk.OptionMenu(row2, self.feed_var, *_FEEDING_ORIENTATION_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row3 = tk.Frame(controls)
        row3.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row3, text="Read direction:", width=18, anchor="w").pack(side=tk.LEFT)
        self.read_var = tk.StringVar(value=_READ_DIRECTION_OPTIONS[0])
        tk.OptionMenu(row3, self.read_var, *_READ_DIRECTION_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row4 = tk.Frame(controls)
        row4.pack(fill=tk.X)
        self.annotate_var = tk.BooleanVar(value=True)
        tk.Checkbutton(row4, text="Show orientation/read annotations on plot", variable=self.annotate_var).pack(side=tk.LEFT)

        actions = tk.Frame(left_panel)
        actions.pack(fill=tk.X, pady=(10, 0))

        tk.Button(
            actions,
            text="Generate Sequence Signal",
            command=self._generate,
        ).pack(side=tk.LEFT)

        self.summary_var = tk.StringVar(value="Provide a sequence and generate a consensus preview.")
        tk.Label(left_panel, textvariable=self.summary_var, anchor="w", fg="#333333").pack(fill=tk.X, pady=(10, 0))

        tk.Label(right_panel, text="Design Notes / Instructions", anchor="w", font=("TkDefaultFont", 10, "bold")).pack(fill=tk.X)
        notes = scrolledtext.ScrolledText(right_panel, height=24, wrap=tk.WORD)
        notes.pack(fill=tk.BOTH, expand=True, pady=(4, 0))
        notes.insert("1.0", _INSTRUCTION_TEXT)
        notes.configure(state="disabled")

    def _generate(self) -> None:
        raw_sequence = self.sequence_box.get("1.0", tk.END)
        feed = self.feed_var.get().strip()
        read_direction = self.read_var.get().strip()

        try:
            sequence = sanitize_sequence(raw_sequence)
            kmer_size = int(self.kmer_var.get().strip())

            # Map feed direction into the strand orientation accepted by
            # consensus_maker_gui helper contracts.
            orientation = "5' forwards" if feed.startswith("5'") else "3' backwards"
            signal = consensus_signal(sequence, kmer_size=kmer_size, orientation=orientation)
            signal = self._apply_display_direction(signal, feed, read_direction)
        except ValueError as exc:
            messagebox.showerror("Invalid input", str(exc))
            return

        self._plot_signal(signal, kmer_size, feed, read_direction)

    def _apply_display_direction(
        self,
        signal: np.ndarray,
        feeding_orientation: str,
        read_direction: str,
    ) -> np.ndarray:
        output = signal.copy()
        if feeding_orientation.startswith("3'"):
            output = output[::-1]
        if read_direction == "right-to-left":
            output = output[::-1]
        return output

    def _plot_signal(
        self,
        signal: np.ndarray,
        kmer_size: int,
        feeding_orientation: str,
        read_direction: str,
    ) -> None:
        mean_level = float(np.mean(signal))
        self.summary_var.set(
            "Generated "
            f"{len(signal)} levels (k={kmer_size}, feed={feeding_orientation}, read={read_direction}). "
            f"Mean normalized current: {mean_level:.3f}"
        )

        fig, ax = plt.subplots(figsize=(10.5, 4.8))
        x = np.arange(len(signal))
        ax.step(x, signal, where="mid", linewidth=1.8)
        ax.set_title("Expected Consensus Signal")
        ax.set_xlabel("k-mer index")
        ax.set_ylabel("Normalized current (I/I0)")
        ax.set_ylim(0.0, 1.0)
        ax.grid(alpha=0.3)

        if self.annotate_var.get():
            annotation = (
                f"Feed: {feeding_orientation}\n"
                f"Read: {read_direction}\n"
                f"k-mer: {kmer_size}"
            )
            ax.text(
                0.99,
                0.02,
                annotation,
                transform=ax.transAxes,
                fontsize=9,
                ha="right",
                va="bottom",
                bbox={"boxstyle": "round,pad=0.3", "facecolor": "white", "alpha": 0.75},
            )

        fig.tight_layout()
        plt.show()


def run_gui() -> None:
    root = tk.Tk()
    app = SequenceDesignerGUI(root)
    _ = app
    root.mainloop()


if __name__ == "__main__":
    run_gui()
