"""Sequence designer GUI with MATLAB-aligned orientation controls.

Deterministic fallback generated by runtime when model-authored implement
actions are unavailable. The scaffold intentionally includes mlapp-style
controls (feeding orientation, pore orientation, display order,
phase shift, and operator notes panel)
so operator-assistant driven runs stay useful under fallback conditions.
"""

from __future__ import annotations

import tkinter as tk
from tkinter import messagebox, scrolledtext

import matplotlib.pyplot as plt
import numpy as np

from nanoporethon.consensus_maker_gui import consensus_signal, sanitize_sequence


_FEEDING_ORIENTATION_OPTIONS = (
    "5'",
    "3'",
)

_PORE_ORIENTATION_OPTIONS = (
    "forwards",
    "backwards",
)

_DISPLAY_ORDER_OPTIONS = (
    "5'→3'",
    "3'→5'",
)

_INSTRUCTION_TEXT = (
    "Sequence Designer Notes\n"
    "----------------------\n"
    "1) Paste an A/C/G/T sequence (whitespace is ignored).\n"
    "2) Set k-mer size and orientation/display controls.\n"
    "3) Generate to inspect expected consensus current levels.\n"
    "4) Tune phase shift (0 to 1) to offset displayed trace indexing.\n"
    "\n"
    "Notation:\n"
    "- Feeding orientation: 5' or 3'.\n"
    "- Pore orientation: forwards or backwards.\n"
    "- Display order: 5'→3' or 3'→5'.\n"
    "- Phase shift: normalized offset in [0, 1].\n"
    "- Current is plotted in normalized I/I0 units.\n"
)


class SequenceDesignerGUI:
    """GUI for sequence-to-consensus previews with mlapp-style controls."""

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Sequence Designer")
        self.root.geometry("1120x700")

        main = tk.Frame(root, padx=10, pady=10)
        main.pack(fill=tk.BOTH, expand=True)

        header = tk.Frame(main)
        header.pack(fill=tk.X, pady=(0, 8))
        tk.Label(
            header,
            text="Sequence Designer",
            font=("TkDefaultFont", 14, "bold"),
            anchor="w",
        ).pack(side=tk.LEFT)
        tk.Label(
            header,
            text="Consensus signal preview from DNA sequence",
            fg="#444444",
        ).pack(side=tk.LEFT, padx=(12, 0))

        content = tk.Frame(main)
        content.pack(fill=tk.BOTH, expand=True)

        left_panel = tk.Frame(content)
        left_panel.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=(0, 10))

        right_panel = tk.Frame(content, width=340)
        right_panel.pack(side=tk.RIGHT, fill=tk.BOTH)
        right_panel.pack_propagate(False)

        tk.Label(left_panel, text="DNA sequence input (5' to 3', A/C/G/T):", anchor="w").pack(fill=tk.X)
        self.sequence_box = scrolledtext.ScrolledText(left_panel, height=12, wrap=tk.WORD)
        self.sequence_box.pack(fill=tk.BOTH, expand=False, pady=(4, 8))

        controls = tk.LabelFrame(left_panel, text="Signal Controls", padx=8, pady=8)
        controls.pack(fill=tk.X)

        row1 = tk.Frame(controls)
        row1.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row1, text="k-mer size:", width=18, anchor="w").pack(side=tk.LEFT)
        self.kmer_var = tk.StringVar(value="5")
        tk.Entry(row1, textvariable=self.kmer_var, width=8).pack(side=tk.LEFT)

        row2 = tk.Frame(controls)
        row2.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row2, text="Feeding orientation:", width=18, anchor="w").pack(side=tk.LEFT)
        self.feed_var = tk.StringVar(value=_FEEDING_ORIENTATION_OPTIONS[0])
        tk.OptionMenu(row2, self.feed_var, *_FEEDING_ORIENTATION_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row3 = tk.Frame(controls)
        row3.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row3, text="Pore orientation:", width=18, anchor="w").pack(side=tk.LEFT)
        self.pore_var = tk.StringVar(value=_PORE_ORIENTATION_OPTIONS[0])
        tk.OptionMenu(row3, self.pore_var, *_PORE_ORIENTATION_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row4 = tk.Frame(controls)
        row4.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row4, text="Display order:", width=18, anchor="w").pack(side=tk.LEFT)
        self.display_order_var = tk.StringVar(value=_DISPLAY_ORDER_OPTIONS[0])
        tk.OptionMenu(row4, self.display_order_var, *_DISPLAY_ORDER_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row5 = tk.Frame(controls)
        row5.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row5, text="Phase shift (0-1):", width=18, anchor="w").pack(side=tk.LEFT)
        self.phase_shift_var = tk.DoubleVar(value=0.0)
        tk.Scale(
            row5,
            from_=0.0,
            to=1.0,
            resolution=0.01,
            orient=tk.HORIZONTAL,
            variable=self.phase_shift_var,
            length=220,
        ).pack(side=tk.LEFT)

        row6 = tk.Frame(controls)
        row6.pack(fill=tk.X)
        self.annotate_var = tk.BooleanVar(value=True)
        tk.Checkbutton(row6, text="Show orientation/phase annotations on plot", variable=self.annotate_var).pack(side=tk.LEFT)

        actions = tk.Frame(left_panel)
        actions.pack(fill=tk.X, pady=(10, 0))

        tk.Button(
            actions,
            text="Generate Sequence Signal",
            command=self._generate,
        ).pack(side=tk.LEFT)

        self.summary_var = tk.StringVar(value="Provide a sequence and generate a consensus preview.")
        tk.Label(left_panel, textvariable=self.summary_var, anchor="w", fg="#333333").pack(fill=tk.X, pady=(10, 0))

        tk.Label(right_panel, text="Design Notes / Instructions", anchor="w", font=("TkDefaultFont", 10, "bold")).pack(fill=tk.X)
        notes = scrolledtext.ScrolledText(right_panel, height=24, wrap=tk.WORD)
        notes.pack(fill=tk.BOTH, expand=True, pady=(4, 0))
        notes.insert("1.0", _INSTRUCTION_TEXT)
        notes.configure(state="disabled")

    def _generate(self) -> None:
        raw_sequence = self.sequence_box.get("1.0", tk.END)
        feed = self.feed_var.get().strip()
        pore_orientation = self.pore_var.get().strip()
        display_order = self.display_order_var.get().strip()
        phase_shift = float(self.phase_shift_var.get())

        try:
            sequence = sanitize_sequence(raw_sequence)
            kmer_size = int(self.kmer_var.get().strip())

            # Map feed direction into the strand orientation accepted by
            # consensus_maker_gui helper contracts.
            orientation = f"{feed} {pore_orientation}"
            signal = consensus_signal(sequence, kmer_size=kmer_size, orientation=orientation)
            signal = self._apply_display_settings(signal, display_order, phase_shift)
        except ValueError as exc:
            messagebox.showerror("Invalid input", str(exc))
            return

        self._plot_signal(signal, kmer_size, feed, pore_orientation, display_order, phase_shift)

    def _apply_display_settings(
        self,
        signal: np.ndarray,
        display_order: str,
        phase_shift: float,
    ) -> np.ndarray:
        output = signal.copy()
        if display_order.startswith("3'"):
            output = output[::-1]
        if len(output) > 1 and phase_shift > 0:
            shift_steps = int(round((phase_shift % 1.0) * (len(output) - 1)))
            if shift_steps:
                output = np.roll(output, shift_steps)
        return output

    def _plot_signal(
        self,
        signal: np.ndarray,
        kmer_size: int,
        feeding_orientation: str,
        pore_orientation: str,
        display_order: str,
        phase_shift: float,
    ) -> None:
        mean_level = float(np.mean(signal))
        self.summary_var.set(
            "Generated "
            f"{len(signal)} levels (k={kmer_size}, feed={feeding_orientation}, "
            f"pore={pore_orientation}, order={display_order}, phase={phase_shift:.2f}). "
            f"Mean normalized current: {mean_level:.3f}"
        )

        fig, ax = plt.subplots(figsize=(10.5, 4.8))
        x = np.arange(len(signal))
        ax.step(x, signal, where="mid", linewidth=1.8)
        ax.set_title("Expected Consensus Signal")
        ax.set_xlabel("k-mer index")
        ax.set_ylabel("Normalized current (I/I0)")
        ax.set_ylim(0.0, 1.0)
        ax.grid(alpha=0.3)

        if self.annotate_var.get():
            annotation = (
                f"Feed: {feeding_orientation}\n"
                f"Pore: {pore_orientation}\n"
                f"Order: {display_order}\n"
                f"Phase: {phase_shift:.2f}\n"
                f"k-mer: {kmer_size}"
            )
            ax.text(
                0.99,
                0.02,
                annotation,
                transform=ax.transAxes,
                fontsize=9,
                ha="right",
                va="bottom",
                bbox={"boxstyle": "round,pad=0.3", "facecolor": "white", "alpha": 0.75},
            )

        fig.tight_layout()
        plt.show()


def run_gui() -> None:
    root = tk.Tk()
    app = SequenceDesignerGUI(root)
    _ = app
    root.mainloop()


if __name__ == "__main__":
    run_gui()
