"""Sequence designer GUI with MATLAB-aligned orientation controls.

Deterministic fallback generated by runtime when model-authored implement
actions are unavailable. The scaffold intentionally includes mlapp-style
controls (feeding orientation, pore orientation, display order,
phase shift, and operator notes panel)
so operator-assistant driven runs stay useful under fallback conditions.
"""

from __future__ import annotations

import json
import random
import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext

import matplotlib.pyplot as plt
import numpy as np


_FEEDING_ORIENTATION_OPTIONS = (
    "5'",
    "3'",
)

_PORE_ORIENTATION_OPTIONS = (
    "forwards",
    "backwards",
)

_DISPLAY_ORDER_OPTIONS = (
    "5'→3'",
    "3'→5'",
)

_INSTRUCTION_TEXT = (
    "Sequence Designer Notes\n"
    "----------------------\n"
    "1) Paste an A/C/G/T sequence (whitespace is ignored).\n"
    "2) Set k-mer size and orientation/display controls.\n"
    "3) Generate to inspect expected consensus current levels.\n"
    "4) Tune phase shift (0 to 1) to offset displayed trace indexing.\n"
    "\n"
    "Notation:\n"
    "- Feeding orientation: 5' or 3'.\n"
    "- Pore orientation: forwards or backwards.\n"
    "- Display order: 5'→3' or 3'→5'.\n"
    "- Phase shift: normalized offset in [0, 1].\n"
    "- Current is plotted in normalized I/I0 units.\n"
)


_BASE_WEIGHTS = {
    "A": 0.18,
    "C": 0.42,
    "G": 0.66,
    "T": 0.90,
}


def sanitize_sequence(sequence: str) -> str:
    """Normalize and validate a DNA sequence."""
    normalized = "".join(sequence.upper().split())
    if not normalized:
        raise ValueError("DNA sequence is empty.")

    invalid = sorted({base for base in normalized if base not in {"A", "C", "G", "T"}})
    if invalid:
        raise ValueError(
            "DNA sequence contains invalid characters: " + ", ".join(invalid)
        )
    return normalized


def reverse_complement(sequence: str) -> str:
    """Return reverse complement in 5'→3' coordinates."""
    translation = str.maketrans("ACGT", "TGCA")
    return sequence.translate(translation)[::-1]


def orient_sequence(sequence: str, orientation: str) -> str:
    """Apply feed/pore orientation combinations for sequence design preview."""
    normalized = orientation.strip().lower()
    mapping = {
        "5' forwards": sequence,
        "5' backwards": sequence[::-1],
        "3' forwards": reverse_complement(sequence),
        "3' backwards": reverse_complement(sequence)[::-1],
    }
    if normalized not in mapping:
        raise ValueError(f"Unsupported orientation: {orientation}")
    return mapping[normalized]


def _kmer_level(kmer: str) -> float:
    if not kmer:
        raise ValueError("k-mer cannot be empty")

    pos_weights = np.linspace(0.85, 1.15, num=len(kmer), dtype=float)
    raw = 0.0
    min_raw = 0.0
    max_raw = 0.0
    for base, pos_weight in zip(kmer, pos_weights):
        if base not in _BASE_WEIGHTS:
            raise ValueError(f"Invalid base in k-mer: {base}")
        min_raw += _BASE_WEIGHTS["A"] * pos_weight
        max_raw += _BASE_WEIGHTS["T"] * pos_weight
        raw += _BASE_WEIGHTS[base] * pos_weight

    if max_raw <= min_raw:
        return 0.2

    unit = (raw - min_raw) / (max_raw - min_raw)
    return 0.2 + 0.7 * float(np.clip(unit, 0.0, 1.0))


def consensus_signal(sequence: str, kmer_size: int = 5, orientation: str = "5' forwards") -> np.ndarray:
    """Compute deterministic expected signal levels from oriented k-mer windows."""
    seq = sanitize_sequence(sequence)
    if kmer_size < 1:
        raise ValueError("kmer_size must be >= 1")
    if len(seq) < kmer_size:
        raise ValueError(
            f"DNA sequence length ({len(seq)}) must be at least kmer_size ({kmer_size})."
        )

    oriented = orient_sequence(seq, orientation)
    levels = [_kmer_level(oriented[i : i + kmer_size]) for i in range(len(oriented) - kmer_size + 1)]
    return np.asarray(levels, dtype=float)


class SequenceDesignerGUI:
    """GUI for sequence-to-consensus previews with mlapp-style controls."""

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Sequence Designer")
        self.root.geometry("1120x700")
        self.last_generated_levels: list[float] = []

        main = tk.Frame(root, padx=10, pady=10)
        main.pack(fill=tk.BOTH, expand=True)

        header = tk.Frame(main)
        header.pack(fill=tk.X, pady=(0, 8))
        tk.Label(
            header,
            text="Sequence Designer",
            font=("TkDefaultFont", 14, "bold"),
            anchor="w",
        ).pack(side=tk.LEFT)
        tk.Label(
            header,
            text="Consensus signal preview from DNA sequence",
            fg="#444444",
        ).pack(side=tk.LEFT, padx=(12, 0))

        content = tk.Frame(main)
        content.pack(fill=tk.BOTH, expand=True)

        left_panel = tk.Frame(content)
        left_panel.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=(0, 10))

        right_panel = tk.Frame(content, width=340)
        right_panel.pack(side=tk.RIGHT, fill=tk.BOTH)
        right_panel.pack_propagate(False)

        tk.Label(left_panel, text="DNA sequence input (5' to 3', A/C/G/T):", anchor="w").pack(fill=tk.X)
        self.sequence_box = scrolledtext.ScrolledText(left_panel, height=12, wrap=tk.WORD)
        self.sequence_box.pack(fill=tk.BOTH, expand=False, pady=(4, 8))
        self.sequence_box.bind("<KeyRelease>", lambda _event: self._refresh_edit_controls())

        controls = tk.LabelFrame(left_panel, text="Signal Controls", padx=8, pady=8)
        controls.pack(fill=tk.X)

        row1 = tk.Frame(controls)
        row1.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row1, text="k-mer size:", width=18, anchor="w").pack(side=tk.LEFT)
        self.kmer_var = tk.StringVar(value="5")
        tk.Entry(row1, textvariable=self.kmer_var, width=8).pack(side=tk.LEFT)

        self.hel308_var = tk.BooleanVar(value=False)
        tk.Checkbutton(
            row1,
            text="Hel308 mode",
            variable=self.hel308_var,
            command=self._toggle_hel308_mode,
        ).pack(side=tk.LEFT, padx=(12, 0))

        row2 = tk.Frame(controls)
        row2.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row2, text="Feeding orientation:", width=18, anchor="w").pack(side=tk.LEFT)
        self.feed_var = tk.StringVar(value=_FEEDING_ORIENTATION_OPTIONS[0])
        tk.OptionMenu(row2, self.feed_var, *_FEEDING_ORIENTATION_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row3 = tk.Frame(controls)
        row3.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row3, text="Pore orientation:", width=18, anchor="w").pack(side=tk.LEFT)
        self.pore_var = tk.StringVar(value=_PORE_ORIENTATION_OPTIONS[0])
        tk.OptionMenu(row3, self.pore_var, *_PORE_ORIENTATION_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row4 = tk.Frame(controls)
        row4.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row4, text="Display order:", width=18, anchor="w").pack(side=tk.LEFT)
        self.display_order_var = tk.StringVar(value=_DISPLAY_ORDER_OPTIONS[0])
        tk.OptionMenu(row4, self.display_order_var, *_DISPLAY_ORDER_OPTIONS).pack(side=tk.LEFT, fill=tk.X, expand=True)

        row5 = tk.Frame(controls)
        row5.pack(fill=tk.X, pady=(0, 6))
        tk.Label(row5, text="Phase shift (0-1):", width=18, anchor="w").pack(side=tk.LEFT)
        self.phase_shift_var = tk.DoubleVar(value=0.0)
        tk.Scale(
            row5,
            from_=0.0,
            to=1.0,
            resolution=0.01,
            orient=tk.HORIZONTAL,
            variable=self.phase_shift_var,
            length=220,
        ).pack(side=tk.LEFT)

        row6 = tk.Frame(controls)
        row6.pack(fill=tk.X)
        self.annotate_var = tk.BooleanVar(value=True)
        tk.Checkbutton(row6, text="Show orientation/phase annotations on plot", variable=self.annotate_var).pack(side=tk.LEFT)

        editing = tk.LabelFrame(left_panel, text="Edit Sequence at N", padx=8, pady=8)
        editing.pack(fill=tk.X, pady=(10, 0))

        edit_row1 = tk.Frame(editing)
        edit_row1.pack(fill=tk.X, pady=(0, 6))
        tk.Label(edit_row1, text="Edit position:", width=18, anchor="w").pack(side=tk.LEFT)
        self.edit_index_var = tk.IntVar(value=1)
        self.edit_index_entry_var = tk.StringVar(value="1")
        self.edit_slider = tk.Scale(
            edit_row1,
            from_=1,
            to=1,
            orient=tk.HORIZONTAL,
            variable=self.edit_index_var,
            command=self._on_edit_slider_change,
            length=220,
        )
        self.edit_slider.pack(side=tk.LEFT)
        tk.Entry(edit_row1, textvariable=self.edit_index_entry_var, width=6).pack(side=tk.LEFT, padx=(8, 0))
        tk.Button(edit_row1, text="Set", command=self._set_edit_index_from_entry).pack(side=tk.LEFT, padx=(6, 0))

        edit_row2 = tk.Frame(editing)
        edit_row2.pack(fill=tk.X)
        for base in ("A", "C", "G", "T"):
            tk.Button(edit_row2, text=base, width=4, command=lambda b=base: self._apply_base_edit(b)).pack(side=tk.LEFT, padx=(0, 4))
        tk.Button(edit_row2, text="Delete", command=self._delete_base_at_edit).pack(side=tk.LEFT, padx=(8, 4))
        tk.Button(edit_row2, text="Random", command=self._random_base_at_edit).pack(side=tk.LEFT)

        actions = tk.Frame(left_panel)
        actions.pack(fill=tk.X, pady=(10, 0))

        tk.Button(
            actions,
            text="Generate Sequence Signal",
            command=self._generate,
        ).pack(side=tk.LEFT)
        tk.Button(actions, text="Save Figure", command=self._save_current_figure).pack(side=tk.LEFT, padx=(8, 0))
        tk.Button(actions, text="Export Levels", command=self._export_levels).pack(side=tk.LEFT, padx=(8, 0))

        self.summary_var = tk.StringVar(value="Provide a sequence and generate a consensus preview.")
        tk.Label(left_panel, textvariable=self.summary_var, anchor="w", fg="#333333").pack(fill=tk.X, pady=(10, 0))

        tk.Label(right_panel, text="Design Notes / Instructions", anchor="w", font=("TkDefaultFont", 10, "bold")).pack(fill=tk.X)
        notes = scrolledtext.ScrolledText(right_panel, height=24, wrap=tk.WORD)
        notes.pack(fill=tk.BOTH, expand=True, pady=(4, 0))
        notes.insert("1.0", _INSTRUCTION_TEXT)
        notes.configure(state="disabled")
        self._refresh_edit_controls()

    def _generate(self) -> None:
        raw_sequence = self.sequence_box.get("1.0", tk.END)
        feed = self.feed_var.get().strip()
        pore_orientation = self.pore_var.get().strip()
        display_order = self.display_order_var.get().strip()
        phase_shift = float(self.phase_shift_var.get())

        try:
            sequence = sanitize_sequence(raw_sequence)
            kmer_size = int(self.kmer_var.get().strip())

            orientation = f"{feed} {pore_orientation}"
            signal = consensus_signal(sequence, kmer_size=kmer_size, orientation=orientation)
            signal = self._apply_display_settings(signal, display_order, phase_shift)
        except ValueError as exc:
            messagebox.showerror("Invalid input", str(exc))
            return

        self.last_generated_levels = signal.tolist()

        self._plot_signal(signal, kmer_size, feed, pore_orientation, display_order, phase_shift)

    def _toggle_hel308_mode(self) -> None:
        if self.hel308_var.get():
            self.kmer_var.set("6")
            self.summary_var.set("Hel308 mode enabled (k-mer default set to 6).")
        elif self.kmer_var.get().strip() == "6":
            self.kmer_var.set("5")

    def _refresh_edit_controls(self) -> None:
        raw = self.sequence_box.get("1.0", tk.END)
        length = len("".join(raw.upper().split()))
        max_index = max(1, length + 1)
        self.edit_slider.configure(to=max_index)
        if self.edit_index_var.get() > max_index:
            self.edit_index_var.set(max_index)
            self.edit_index_entry_var.set(str(max_index))

    def _on_edit_slider_change(self, _value: str) -> None:
        self.edit_index_entry_var.set(str(self.edit_index_var.get()))

    def _set_edit_index_from_entry(self) -> None:
        try:
            idx = int(self.edit_index_entry_var.get().strip())
        except ValueError:
            messagebox.showerror("Invalid edit index", "Edit position must be an integer.")
            return
        idx = max(1, min(idx, int(float(self.edit_slider.cget("to")))))
        self.edit_index_var.set(idx)
        self.edit_index_entry_var.set(str(idx))

    def _current_sequence(self) -> str:
        return "".join(self.sequence_box.get("1.0", tk.END).upper().split())

    def _set_sequence(self, sequence: str) -> None:
        self.sequence_box.delete("1.0", tk.END)
        self.sequence_box.insert("1.0", sequence)
        self._refresh_edit_controls()

    def _apply_base_edit(self, base: str) -> None:
        seq = self._current_sequence()
        idx = self.edit_index_var.get() - 1
        if idx >= len(seq):
            new_seq = seq + base
        else:
            new_seq = seq[:idx] + base + seq[idx + 1 :]
        self._set_sequence(new_seq)

    def _delete_base_at_edit(self) -> None:
        seq = self._current_sequence()
        if not seq:
            return
        idx = self.edit_index_var.get() - 1
        if idx >= len(seq):
            new_seq = seq[:-1]
        else:
            new_seq = seq[:idx] + seq[idx + 1 :]
        self._set_sequence(new_seq)

    def _random_base_at_edit(self) -> None:
        self._apply_base_edit(random.choice(["A", "C", "G", "T"]))

    def _save_current_figure(self) -> None:
        fig = plt.gcf() if plt.get_fignums() else None
        if fig is None:
            messagebox.showinfo("No figure", "Generate a signal before saving a figure.")
            return
        target = filedialog.asksaveasfilename(
            title="Save sequence designer figure",
            defaultextension=".png",
            filetypes=[("PNG", "*.png"), ("PDF", "*.pdf"), ("All files", "*.*")],
        )
        if not target:
            return
        fig.savefig(target, dpi=200)
        self.summary_var.set(f"Saved figure: {target}")

    def _export_levels(self) -> None:
        if not self.last_generated_levels:
            messagebox.showinfo("No data", "Generate a signal before exporting levels.")
            return
        target = filedialog.asksaveasfilename(
            title="Export predicted levels",
            defaultextension=".json",
            filetypes=[("JSON", "*.json"), ("All files", "*.*")],
        )
        if not target:
            return

        payload = {
            "sequence_5_to_3": self._current_sequence(),
            "kmer_size": int(self.kmer_var.get().strip()),
            "feeding_orientation": self.feed_var.get().strip(),
            "pore_orientation": self.pore_var.get().strip(),
            "display_order": self.display_order_var.get().strip(),
            "phase_shift": float(self.phase_shift_var.get()),
            "hel308_mode": bool(self.hel308_var.get()),
            "levels": self.last_generated_levels,
        }
        with open(target, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2)
        self.summary_var.set(f"Exported levels: {target}")

    def _apply_display_settings(
        self,
        signal: np.ndarray,
        display_order: str,
        phase_shift: float,
    ) -> np.ndarray:
        output = signal.copy()
        if display_order.startswith("3'"):
            output = output[::-1]
        if len(output) > 1 and phase_shift > 0:
            shift_steps = int(round((phase_shift % 1.0) * (len(output) - 1)))
            if shift_steps:
                output = np.roll(output, shift_steps)
        return output

    def _plot_signal(
        self,
        signal: np.ndarray,
        kmer_size: int,
        feeding_orientation: str,
        pore_orientation: str,
        display_order: str,
        phase_shift: float,
    ) -> None:
        mean_level = float(np.mean(signal))
        self.summary_var.set(
            "Generated "
            f"{len(signal)} levels (k={kmer_size}, feed={feeding_orientation}, "
            f"pore={pore_orientation}, order={display_order}, phase={phase_shift:.2f}). "
            f"Mean normalized current: {mean_level:.3f}"
        )

        fig, ax = plt.subplots(figsize=(10.5, 4.8))
        x = np.arange(len(signal))
        ax.step(x, signal, where="mid", linewidth=1.8)
        ax.set_title("Expected Consensus Signal")
        ax.set_xlabel("k-mer index")
        ax.set_ylabel("Normalized current (I/I0)")
        ax.set_ylim(0.0, 1.0)
        ax.grid(alpha=0.3)

        if self.annotate_var.get():
            annotation = (
                f"Feed: {feeding_orientation}\n"
                f"Pore: {pore_orientation}\n"
                f"Order: {display_order}\n"
                f"Phase: {phase_shift:.2f}\n"
                f"k-mer: {kmer_size}"
            )
            ax.text(
                0.99,
                0.02,
                annotation,
                transform=ax.transAxes,
                fontsize=9,
                ha="right",
                va="bottom",
                bbox={"boxstyle": "round,pad=0.3", "facecolor": "white", "alpha": 0.75},
            )

        fig.tight_layout()
        plt.show()


def run_gui() -> None:
    root = tk.Tk()
    app = SequenceDesignerGUI(root)
    _ = app
    root.mainloop()


if __name__ == "__main__":
    run_gui()
